---
on:          # yamllint disable-line rule:truthy
  push:
    branches: main
  pull_request:
    branches: main
name: Integration tests

jobs:
  integration-tests:
    uses: coreruleset/crs-plugin-test-action/.github/workflows/integration.yaml@v2.0.0
