---
on:          # yamllint disable-line rule:truthy
  push:
    branches: main
  pull_request:
    branches: main
name: Integration tests

jobs:
  integration-tests:
    uses: coreruleset/crs-plugin-test-action/.github/workflows/integration.yaml@580582e7ca3ea87aa31631893048a2fc074b9b03 # v2.0.0
